runtime: php55
api_version: 1
threadsafe: true

handlers:

- url: /styles/(.*\.css)
  mime_type: text/css
  static_files: examples/styles/\1
  upload: examples/styles/(.*\.css)

- url: /favicon.ico
  mime_type: image/x-icon
  static_files: examples/favicon.ico
  upload: examples/favicon.ico

- url: /main
  script: examples/main.php

- url: /curl
  script: examples/curl.php